DROP TABLE DU;

CREATE EXTERNAL TABLE I_DU (
  SCENARIO_ID                      INT
, ENB_ID                           STRING
, E_NODEB_NM                       STRING
, PCI_CNT                          INT
, STRMAKER                         STRING
, REG_DT                           STRING
)
PARTITIONED BY (SCENARIO_ID INT)
COMMENT 'SCENARIO'
STORED AS PARQUET
LOCATION '/teos/warehouse/DU';
--
ALTER TABLE SCHEDULE ADD PARTITION (SCHEDULE_ID=8459967);
ALTER TABLE SCENARIO ADD PARTITION (SCENARIO_ID=8459967) LOCATION '/teos/warehouse/SCENARIO/SCENARIO_ID=8459967';
ALTER TABLE SCENARIO DROP PARTITION (SCENARIO_ID=8459967);