--DROP TABLE I_FABASE;

CREATE EXTERNAL TABLE I_FABASE
(
 FA_SEQ               INT
,SYSTEMTYPE           INT
,CHNO                 INT
,UPLINKFREQ           INT
,DOWNLINKFREQ         INT
,ANALY_CHECK          INT
,PASSLOSS_MODEL       STRING
,FREQ                 STRING
,UPLINKFREQ_COMMENT   STRING
,DOWNLINKFREQ_COMMENT STRING
,REG_DT               STRING
,REG_ID               STRING
)
STORED AS PARQUET
LOCATION '/teos/warehouse/FABASE'
;
