DROP TABLE SCHEDULE;

CREATE TABLE SCHEDULE (
  SCHEDULE_ID               STRING
, TYPE_CD                   STRING
, SCENARIO_ID               STRING
, USER_ID                   STRING
, PRIORITIZE                STRING
, PROCESS_CD                STRING
, PROCESS_MSG               STRING
, SCENARIO_PATH             STRING
, REG_DT                    STRING
, MODIFY_DT                 STRING
, RETRY_CNT                 STRING
, SERVER_ID                 STRING
, BIN_X_CNT                 STRING
, BIN_Y_CNT                 STRING
, RU_CNT                    STRING
, ANALYSIS_WEIGHT           STRING
, PHONE_NO                  STRING
, RESULT_TIME               STRING
, TILT_PROCESS_TYPE         STRING
, GEOMETRYQUERY_SCHEDULE_ID STRING
, RESULT_BIT                STRING
, INTERWORKING_INFO         STRING
)
COMMENT 'SCHEDULE'
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '|'
LINES TERMINATED BY '\n'
STORED AS PARQUET;
--STORED AS TEXTFILE;
--LOCATION '/user/teos/hive/SCHEDULE_8443705';

LOAD DATA INPATH '/user/teos/sam/entity/SCHEDULE_8443705.dat' INTO TABLE SCHEDULE;
LOAD DATA INPATH '/user/teos/parquet/entity/SCHEDULE/SCHEDULE_8443705' INTO TABLE SCHEDULE;




SELECT * FROM SCHEDULE;

SELECT COUNT(*) FROM SCHEDULE;


CREATE TABLE SCHEDULE2 AS SELECT * FROM SCHEDULE;

DESCRIBE DATABASE default;