package com.sccomz.scala.schema

import org.apache.spark.sql.types.StructType
import org.apache.spark.sql.types.StructField
import org.apache.spark.sql.types.StringType
import org.apache.spark.sql.types.IntegerType
import org.apache.spark.sql.types.FloatType

object NRUETRAFFIC{
final val schema : StructType= StructType( Array(
 StructField("SYSTEM_ID"      , IntegerType)
,StructField("FA_SEQ"         , IntegerType)
,StructField("DLUL_TYPE"      , IntegerType)
,StructField("RX_MODULATION"  , IntegerType)
,StructField("RX_LAYER"       , IntegerType)
,StructField("MODULATION1"    , FloatType)
,StructField("MODULATION2"    , FloatType)
,StructField("MODULATION3"    , FloatType)
,StructField("MODULATION4"    , FloatType)
,StructField("MODULATION5"    , FloatType)
,StructField("MODULATION6"    , FloatType)
,StructField("MODULATION7"    , FloatType)
,StructField("MODULATION8"    , FloatType)
,StructField("MODULATION9"    , FloatType)
,StructField("MODULATION10"   , FloatType)
,StructField("MODULATION11"   , FloatType)
,StructField("MODULATION12"   , FloatType)
,StructField("MODULATION13"   , FloatType)
,StructField("MODULATION14"   , FloatType)
,StructField("MODULATION15"   , FloatType)
,StructField("LAYER1"         , FloatType)
,StructField("LAYER2"         , FloatType)
,StructField("LAYER3"         , FloatType)
,StructField("LAYER4"         , FloatType)
,StructField("LAYER5"         , FloatType)
,StructField("LAYER6"         , FloatType)
,StructField("LAYER7"         , FloatType)
,StructField("LAYER8"         , FloatType)
,StructField("LAYER9"         , FloatType)
,StructField("LAYER10"        , FloatType)
,StructField("LAYER11"        , FloatType)
,StructField("LAYER12"        , FloatType)
,StructField("LAYER13"        , FloatType)
,StructField("LAYER14"        , FloatType)
,StructField("LAYER15"        , FloatType)
,StructField("CODERATE1"      , FloatType)
,StructField("CODERATE2"      , FloatType)
,StructField("CODERATE3"      , FloatType)
,StructField("CODERATE4"      , FloatType)
,StructField("CODERATE5"      , FloatType)
,StructField("CODERATE6"      , FloatType)
,StructField("CODERATE7"      , FloatType)
,StructField("CODERATE8"      , FloatType)
,StructField("CODERATE9"      , FloatType)
,StructField("CODERATE10"     , FloatType)
,StructField("CODERATE11"     , FloatType)
,StructField("CODERATE12"     , FloatType)
,StructField("CODERATE13"     , FloatType)
,StructField("CODERATE14"     , FloatType)
,StructField("CODERATE15"     , FloatType)
,StructField("SNR1"           , FloatType)
,StructField("SNR2"           , FloatType)
,StructField("SNR3"           , FloatType)
,StructField("SNR4"           , FloatType)
,StructField("SNR5"           , FloatType)
,StructField("SNR6"           , FloatType)
,StructField("SNR7"           , FloatType)
,StructField("SNR8"           , FloatType)
,StructField("SNR9"           , FloatType)
,StructField("SNR10"          , FloatType)
,StructField("SNR11"          , FloatType)
,StructField("SNR12"          , FloatType)
,StructField("SNR13"          , FloatType)
,StructField("SNR14"          , FloatType)
,StructField("SNR15"          , FloatType)
,StructField("SCENARIO_ID"    , IntegerType)

))
}