package com.sccomz.scala.schema

import org.apache.spark.sql.types.StructType
import org.apache.spark.sql.types.StructField
import org.apache.spark.sql.types.StringType

object SCENARIO {
final val schema : StructType= StructType( Array(
 StructField("SCENARIO_NM"            ,StringType)
,StructField("USER_ID"                ,StringType)
,StructField("SYSTEM_ID"              ,StringType)
,StructField("NETWORK_TYPE"           ,StringType)
,StructField("SIDO_CD"                ,StringType)
,StructField("SIGUGUN_CD"             ,StringType)
,StructField("DONG_CD"                ,StringType)
,StructField("SIDO"                   ,StringType)
,StructField("SIGUGUN"                ,StringType)
,StructField("DONG"                   ,StringType)
,StructField("STARTX"                 ,StringType)
,StructField("STARTY"                 ,StringType)
,StructField("ENDX"                   ,StringType)
,StructField("ENDY"                   ,StringType)
,StructField("FA_MODEL_ID"            ,StringType)
,StructField("FA_SEQ"                 ,StringType)
,StructField("SCENARIO_DESC"          ,StringType)
,StructField("USE_BUILDING"           ,StringType)
,StructField("USE_MULTIFA"            ,StringType)
,StructField("PRECISION"              ,StringType)
,StructField("PWRCTRLCHECKPOINT"      ,StringType)
,StructField("MAXITERATIONPWRCTRL"    ,StringType)
,StructField("RESOLUTION"             ,StringType)
,StructField("MODEL_RADIUS"           ,StringType)
,StructField("REG_DT"                 ,StringType)
,StructField("MODIFY_DT"              ,StringType)
,StructField("UPPER_SCENARIO_ID"      ,StringType)
,StructField("FLOORBUILDING"          ,StringType)
,StructField("FLOOR"                  ,StringType)
,StructField("FLOORLOSS"              ,StringType)
,StructField("SCENARIO_SUB_ID"        ,StringType)
,StructField("SCENARIO_SOLUTION_NUM"  ,StringType)
,StructField("LOSS_TYPE"              ,StringType)
,StructField("RU_CNT"                 ,StringType)
,StructField("MODIFY_YN"              ,StringType)
,StructField("BATCH_YN"               ,StringType)
,StructField("TM_STARTX"              ,StringType)
,StructField("TM_STARTY"              ,StringType)
,StructField("TM_ENDX"                ,StringType)
,StructField("TM_ENDY"                ,StringType)
,StructField("REAL_DATE"              ,StringType)
,StructField("REAL_DRM_FILE"          ,StringType)
,StructField("REAL_COMP"              ,StringType)
,StructField("REAL_CATT"              ,StringType)
,StructField("REAL_CATY"              ,StringType)
,StructField("BLD_TYPE"               ,StringType)
,StructField("SCENARIO_ID"            ,StringType)
))
}
