DROP TABLE SCHEDULE;

CREATE EXTERNAL TABLE SCHEDULE (
  TYPE_CD                   STRING
, SCENARIO_ID               STRING
, USER_ID                   STRING
, PRIORITIZE                STRING
, PROCESS_CD                STRING
, PROCESS_MSG               STRING
, SCENARIO_PATH             STRING
, REG_DT                    STRING
, MODIFY_DT                 STRING
, RETRY_CNT                 STRING
, SERVER_ID                 STRING
, BIN_X_CNT                 STRING
, BIN_Y_CNT                 STRING
, RU_CNT                    STRING
, ANALYSIS_WEIGHT           STRING
, PHONE_NO                  STRING
, RESULT_TIME               STRING
, TILT_PROCESS_TYPE         STRING
, GEOMETRYQUERY_SCHEDULE_ID STRING
, RESULT_BIT                STRING
, INTERWORKING_INFO         STRING
)
PARTITIONED BY (SCHEDULE_ID INT)
COMMENT 'SCHEDULE'
--ROW FORMAT DELIMITED
--FIELDS TERMINATED BY '|'
--LINES TERMINATED BY '\n'
STORED AS PARQUET
--STORED AS TEXTFILE;
--LOCATION '/user/teos/parquet/entity/SCHEDULE';
LOCATION '/user/hive/warehouse/SCHEDULE';

--ALTER TABLE SCHEDULE ADD PARTITION (SCHEDULE_ID=8459967);
--ALTER TABLE SCHEDULE ADD PARTITION (SCHEDULE_ID=8459967) LOCATION '/user/teos/parquet/entity/SCHEDULE/SCHEDULE_ID=8459967'; 
ALTER TABLE SCHEDULE ADD PARTITION (SCHEDULE_ID=8459967) LOCATION '/user/hive/warehouse/SCHEDULE/SCHEDULE_ID=8459967'; 
ALTER TABLE SCHEDULE DROP PARTITION (SCHEDULE_ID=8459967)

SHOW PARTITIONS SCHEDULE;

msck repair table SCHEDULE;


LOAD DATA INPATH '/user/teos/sam/entity/SCHEDULE_8443705.dat' INTO TABLE SCHEDULE;
LOAD DATA INPATH '/user/teos/parquet/entity/SCHEDULE' INTO TABLE SCHEDULE;


SELECT * FROM I_SCHEDULE;
SELECT * FROM I_SCENARIO;
