-----------------------------------------
-- I_SCHEDULE
-----------------------------------------

-- DROP TABLE public.schedule;
CREATE TABLE PUBLIC.I_SCHEDULE (
	SCHEDULE_ID NUMERIC NULL,
	TYPE_CD VARCHAR(10) NULL,
	SCENARIO_ID NUMERIC NULL,
	USER_ID VARCHAR(13) NULL,
	PRIORITIZE VARCHAR(20) NULL,
	PROCESS_CD VARCHAR(20) NULL,
	PROCESS_MSG VARCHAR(1500) NULL,
	SCENARIO_PATH VARCHAR(256) NULL,
	REG_DT DATE NULL,
	MODIFY_DT DATE NULL,
	RETRY_CNT NUMERIC NULL,
	SERVER_ID VARCHAR(10) NULL,
	BIN_X_CNT NUMERIC NULL,
	BIN_Y_CNT NUMERIC NULL,
	RU_CNT NUMERIC NULL,
	ANALYSIS_WEIGHT NUMERIC NULL,
	PHONE_NO VARCHAR(12) NULL,
	RESULT_TIME NUMERIC NULL,
	TILT_PROCESS_TYPE NUMERIC NULL,
	GEOMETRYQUERY_SCHEDULE_ID NUMERIC NULL,
	RESULT_BIT BPCHAR(8) NULL,
	INTERWORKING_INFO VARCHAR(200) NULL
);

CREATE INDEX I_SCHEDULE_IDX ON PUBLIC.I_SCHEDULE USING BTREE (SCENARIO_ID, SCHEDULE_ID);
ALTER TABLE PUBLIC.I_SCHEDULE OWNER TO POSTGRES;
GRANT ALL ON TABLE PUBLIC.I_SCHEDULE TO POSTGRES;

-----------------------------------------
-- I_SCENARIO
-----------------------------------------
-- DROP TABLE PUBLIC.I_SCENARIO;

CREATE TABLE PUBLIC.I_SCENARIO (
	SCENARIO_ID NUMERIC NULL,
	SCENARIO_NM VARCHAR(200) NULL,
	USER_ID VARCHAR(13) NULL,
	SYSTEM_ID NUMERIC NULL,
	NETWORK_TYPE NUMERIC NULL,
	SIDO_CD VARCHAR(10) NULL,
	SIGUGUN_CD VARCHAR(10) NULL,
	DONG_CD VARCHAR(10) NULL,
	SIDO VARCHAR(30) NULL,
	SIGUGUN VARCHAR(30) NULL,
	DONG VARCHAR(30) NULL,
	STARTX NUMERIC NULL,
	STARTY NUMERIC NULL,
	ENDX NUMERIC NULL,
	ENDY NUMERIC NULL,
	FA_MODEL_ID NUMERIC NULL,
	FA_SEQ NUMERIC NULL,
	SCENARIO_DESC VARCHAR(500) NULL,
	USE_BUILDING NUMERIC NULL,
	USE_MULTIFA NUMERIC NULL,
	PRECISION NUMERIC NULL,
	PWRCTRLCHECKPOINT NUMERIC NULL,
	MAXITERATIONPWRCTRL NUMERIC NULL,
	RESOLUTION NUMERIC NULL,
	MODEL_RADIUS NUMERIC NULL,
	REG_DT DATE NULL,
	MODIFY_DT DATE NULL,
	UPPER_SCENARIO_ID NUMERIC NULL,
	FLOORBUILDING NUMERIC NULL,
	FLOOR NUMERIC NULL,
	FLOORLOSS NUMERIC NULL,
	SCENARIO_SUB_ID NUMERIC NULL,
	SCENARIO_SOLUTION_NUM NUMERIC NULL,
	LOSS_TYPE NUMERIC NULL,
	RU_CNT NUMERIC NULL,
	MODIFY_YN BPCHAR(1) NULL DEFAULT 'N'::BPCHAR,
	BATCH_YN BPCHAR(1) NULL DEFAULT 'N'::BPCHAR,
	TM_STARTX NUMERIC NULL,
	TM_STARTY NUMERIC NULL,
	TM_ENDX NUMERIC NULL,
	TM_ENDY NUMERIC NULL,
	REAL_DATE VARCHAR(10) NULL,
	REAL_DRM_FILE VARCHAR(100) NULL,
	REAL_COMP VARCHAR(16) NULL,
	REAL_CATT VARCHAR(10) NULL,
	REAL_CATY VARCHAR(1) NULL,
	BLD_TYPE VARCHAR(20) NULL,
	RET_PERIOD NUMERIC NULL,
	RET_END_DATETIME VARCHAR(10) NULL,
	BUILDINGANALYSIS3D_YN VARCHAR(1) NULL,
	BUILDINGANALYSIS3D_RESOLUTION NUMERIC NULL,
	AREA_ID NUMERIC NULL,
	BUILDINGANALYSIS3D_RELATED_YN VARCHAR(1) NULL,
	RELATED_ANALYSIS_COVLIMITRSRP NUMERIC NULL
);
CREATE INDEX I_SCENARIO_IDX ON PUBLIC.I_SCENARIO USING BTREE (SCENARIO_ID);

ALTER TABLE PUBLIC.I_SCENARIO OWNER TO POSTGRES;
GRANT ALL ON TABLE PUBLIC.I_SCENARIO TO POSTGRES;


